package com.resumeai.service;

import com.resumeai.dto.GeminiResponseDto;
import com.resumeai.dto.ResumeAnalysisResponse;
import com.resumeai.model.ATSResult;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.poi.xwpf.model.XWPFHeaderFooterPolicy;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFFooter;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

@Service
public class ReportExportService {

    private static final String REPORT_TITLE = "Resume ATS Report";
    private static final String FOOTER_TEXT = "Design and Develop by Sreeshanth";
    private static final String RESPONSIBILITY_NOTE = "Automated guidance can make mistakes. Verify details responsibly before using this report.";

    public byte[] generatePdfReport(ResumeAnalysisResponse response) throws IOException {
        try (PDDocument document = new PDDocument();
             ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            PdfWriter writer = new PdfWriter(document);

            writer.writeTitle(REPORT_TITLE);
            writer.writeMuted("Generated by Pilot");
            writer.writeMuted(RESPONSIBILITY_NOTE);
            writer.addSpace(12);

            for (ReportSection section : buildSections(response)) {
                writer.writeSection(section);
            }

            writer.close();
            document.save(outputStream);
            return outputStream.toByteArray();
        }
    }

    public byte[] generateWordReport(ResumeAnalysisResponse response) throws IOException {
        try (XWPFDocument document = new XWPFDocument();
             ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            createFooter(document);

            XWPFParagraph title = document.createParagraph();
            title.setAlignment(ParagraphAlignment.LEFT);
            XWPFRun titleRun = title.createRun();
            titleRun.setText(REPORT_TITLE);
            titleRun.setBold(true);
            titleRun.setFontFamily("Arial");
            titleRun.setFontSize(22);
            titleRun.setColor("2563EB");

            addParagraph(document, "Generated by Pilot", false, "6B7280", 10);
            addParagraph(document, RESPONSIBILITY_NOTE, false, "6B7280", 9);

            for (ReportSection section : buildSections(response)) {
                addSection(document, section);
            }

            document.write(outputStream);
            return outputStream.toByteArray();
        }
    }

    private void createFooter(XWPFDocument document) {
        XWPFHeaderFooterPolicy policy = document.createHeaderFooterPolicy();
        XWPFFooter footer = policy.createFooter(XWPFHeaderFooterPolicy.DEFAULT);
        XWPFParagraph footerParagraph = footer.createParagraph();
        footerParagraph.setAlignment(ParagraphAlignment.CENTER);
        XWPFRun footerRun = footerParagraph.createRun();
        footerRun.setText(FOOTER_TEXT);
        footerRun.setFontFamily("Arial");
        footerRun.setFontSize(9);
        footerRun.setColor("6B7280");
    }

    private void addSection(XWPFDocument document, ReportSection section) {
        XWPFParagraph heading = document.createParagraph();
        heading.setSpacingBefore(280);
        heading.setSpacingAfter(100);
        XWPFRun headingRun = heading.createRun();
        headingRun.setText(section.title);
        headingRun.setBold(true);
        headingRun.setFontFamily("Arial");
        headingRun.setFontSize(15);
        headingRun.setColor("111827");

        for (ReportItem item : section.items) {
            XWPFParagraph paragraph = document.createParagraph();
            paragraph.setSpacingAfter(90);
            paragraph.setIndentationLeft(240);

            XWPFRun label = paragraph.createRun();
            label.setText(item.label + ": ");
            label.setBold(true);
            label.setFontFamily("Arial");
            label.setFontSize(10);
            label.setColor("111827");

            XWPFRun value = paragraph.createRun();
            value.setText(clean(item.value));
            value.setFontFamily("Arial");
            value.setFontSize(10);
            value.setColor("374151");
        }
    }

    private void addParagraph(XWPFDocument document, String text, boolean bold, String color, int size) {
        XWPFParagraph paragraph = document.createParagraph();
        paragraph.setSpacingAfter(80);
        XWPFRun run = paragraph.createRun();
        run.setText(clean(text));
        run.setBold(bold);
        run.setFontFamily("Arial");
        run.setFontSize(size);
        run.setColor(color);
    }

    private List<ReportSection> buildSections(ResumeAnalysisResponse response) {
        GeminiResponseDto analysis = response.getAiAnalysis();
        List<ReportSection> sections = new ArrayList<>();

        sections.add(buildScoreSummary(response));
        sections.add(buildStrengths(response, analysis));
        sections.add(buildWeaknesses(response, analysis));
        sections.add(buildRoleMatches(analysis));
        sections.add(buildImprovements(analysis));
        sections.add(buildBulletRewrites(analysis));
        sections.add(buildFormatFit(response, analysis));
        sections.add(buildHrQuestions(response, analysis));
        sections.add(buildFinalRecommendations(analysis));
        sections.add(new ReportSection("10. Responsibility Note", List.of(
                new ReportItem("Note", RESPONSIBILITY_NOTE)
        )));

        return sections;
    }

    private ReportSection buildScoreSummary(ResumeAnalysisResponse response) {
        List<ReportItem> items = new ArrayList<>();
        items.add(new ReportItem("Overall ATS Score", response.getAtsScore() + "/100"));
        items.add(new ReportItem("Status", valueOrDefault(response.getStatus(), "Analysis Complete")));

        ATSResult breakdown = response.getScoreBreakdown();
        if (breakdown != null) {
            items.add(new ReportItem("Keyword Match", breakdown.getKeywordMatch() + "/25"));
            items.add(new ReportItem("Skills Match", breakdown.getSkillsMatch() + "/20"));
            items.add(new ReportItem("Job Alignment", breakdown.getJobDescriptionMatch() + "/15"));
            items.add(new ReportItem("Experience", breakdown.getExperienceRelevance() + "/15"));
            items.add(new ReportItem("ATS Compatibility", breakdown.getAtsCompatibility() + "/10"));
            items.add(new ReportItem("Resume Structure", breakdown.getResumeStructure() + "/10"));
            items.add(new ReportItem("Formatting Quality", breakdown.getFormattingQuality() + "/5"));
        }

        return new ReportSection("1. Score Summary", items);
    }

    private ReportSection buildStrengths(ResumeAnalysisResponse response, GeminiResponseDto analysis) {
        List<ReportItem> items = new ArrayList<>();
        List<Map<String, String>> strengths = analysis == null ? null : analysis.getStrengths();

        if (strengths != null && !strengths.isEmpty()) {
            int index = 1;
            for (Map<String, String> strength : strengths) {
                items.add(new ReportItem("Strength " + index, labeledText(strength, "title", "explanation", "evidence")));
                index++;
            }
        } else if (response.getDetectedSkills() != null && !response.getDetectedSkills().isEmpty()) {
            items.add(new ReportItem("Detected Skills", String.join(", ", response.getDetectedSkills())));
        } else {
            items.add(new ReportItem("Parsed Resume", "Resume text was parsed successfully for ATS scoring."));
        }

        return new ReportSection("2. Strengths", items);
    }

    private ReportSection buildWeaknesses(ResumeAnalysisResponse response, GeminiResponseDto analysis) {
        List<ReportItem> items = new ArrayList<>();
        List<Map<String, String>> weaknesses = analysis == null ? null : analysis.getWeaknesses();

        if (weaknesses != null && !weaknesses.isEmpty()) {
            int index = 1;
            for (Map<String, String> weakness : weaknesses) {
                items.add(new ReportItem("Gap " + index, labeledText(weakness, "title", "explanation", "evidence")));
                index++;
            }
        } else if (response.getMissingKeywords() != null && !response.getMissingKeywords().isEmpty()) {
            items.add(new ReportItem("Missing Keywords", String.join(", ", response.getMissingKeywords())));
        } else {
            items.add(new ReportItem("Keyword Coverage", "No critical deterministic keyword gaps were found."));
        }

        return new ReportSection("3. Weaknesses And Gaps", items);
    }

    private ReportSection buildRoleMatches(GeminiResponseDto analysis) {
        List<ReportItem> items = new ArrayList<>();
        List<Map<String, String>> matches = analysis == null ? null : analysis.getSemanticMatches();

        if (matches != null && !matches.isEmpty()) {
            int index = 1;
            for (Map<String, String> match : matches) {
                items.add(new ReportItem("Match " + index, labeledText(match, "jobRequirement", "resumeEvidence", "matchLevel")));
                index++;
            }
        } else {
            items.add(new ReportItem("Role Matches", "No strong role matches were returned."));
        }

        return new ReportSection("4. Role Matches", items);
    }

    private ReportSection buildImprovements(GeminiResponseDto analysis) {
        List<ReportItem> items = new ArrayList<>();
        List<Map<String, String>> improvements = analysis == null ? null : analysis.getImprovements();

        if (improvements != null && !improvements.isEmpty()) {
            int index = 1;
            for (Map<String, String> improvement : improvements) {
                items.add(new ReportItem("Improvement " + index, "Section: " + valueOrDefault(improvement.get("section"), "Resume")));
                items.add(new ReportItem("Current Problem", valueOrDefault(improvement.get("problem"), "Review this section.")));
                items.add(new ReportItem("Why It Matters", valueOrDefault(improvement.get("whyItMatters"), "This affects recruiter clarity and ATS matching.")));
                items.add(new ReportItem("Recommended Change", valueOrDefault(improvement.get("recommendation"), "Improve this section using truthful resume evidence.")));
                index++;
            }
        } else {
            items.add(new ReportItem("Improvements", "No detailed section improvements were returned."));
        }

        return new ReportSection("5. Ordered Improvements", items);
    }

    private ReportSection buildBulletRewrites(GeminiResponseDto analysis) {
        List<ReportItem> items = new ArrayList<>();
        List<Map<String, String>> rewrites = analysis == null ? null : analysis.getBulletImprovements();

        if (rewrites != null && !rewrites.isEmpty()) {
            int index = 1;
            for (Map<String, String> rewrite : rewrites) {
                items.add(new ReportItem("Bullet " + index, "Before: " + valueOrDefault(rewrite.get("original"), "")));
                items.add(new ReportItem("After", valueOrDefault(rewrite.get("improved"), "")));
                items.add(new ReportItem("Why", valueOrDefault(rewrite.get("reason"), "")));
                index++;
            }
        } else {
            items.add(new ReportItem("Bullet Rewrites", "No bullet rewrite suggestions were returned."));
        }

        return new ReportSection("6. Bullet Rewrites", items);
    }

    private ReportSection buildFormatFit(ResumeAnalysisResponse response, GeminiResponseDto analysis) {
        List<ReportItem> items = new ArrayList<>();
        List<Map<String, String>> suggestions = analysis != null && analysis.getResumeFormatSuggestions() != null && !analysis.getResumeFormatSuggestions().isEmpty()
                ? analysis.getResumeFormatSuggestions()
                : response.getResumeFormatSuggestions();

        if (suggestions != null && !suggestions.isEmpty()) {
            int index = 1;
            for (Map<String, String> suggestion : suggestions) {
                items.add(new ReportItem("Format Change " + index, "Section: " + valueOrDefault(suggestion.get("section"), "Resume Format")));
                items.add(new ReportItem("Current Fit", valueOrDefault(firstValue(suggestion, "currentIssue", "problem"), "Review this section against the company format.")));
                items.add(new ReportItem("Required Change", valueOrDefault(suggestion.get("recommendation"), "Align heading, order, and bullet style to the company template.")));
                index++;
            }
        } else {
            items.add(new ReportItem("Company Format", "Paste the company resume format before analyzing to get format-specific guidance."));
        }

        return new ReportSection("7. Company Format Fit", items);
    }

    private ReportSection buildHrQuestions(ResumeAnalysisResponse response, GeminiResponseDto analysis) {
        List<ReportItem> items = new ArrayList<>();
        List<Map<String, String>> questions = analysis != null && analysis.getHrQuestions() != null && !analysis.getHrQuestions().isEmpty()
                ? analysis.getHrQuestions()
                : response.getHrQuestions();

        if (questions != null && !questions.isEmpty()) {
            int index = 1;
            for (Map<String, String> question : questions) {
                items.add(new ReportItem("Question " + index, valueOrDefault(question.get("question"), "Tell me about yourself.")));
                items.add(new ReportItem("Why HR May Ask", valueOrDefault(question.get("whyAsked"), "To understand your fit for the role.")));
                items.add(new ReportItem("Answer Focus", valueOrDefault(question.get("answerFocus"), "Use a specific resume example and keep it concise.")));
                index++;
            }
        } else {
            items.add(new ReportItem("HR Questions", "Upload a detailed resume to generate likely HR questions."));
        }

        return new ReportSection("8. Likely HR Questions", items);
    }

    private ReportSection buildFinalRecommendations(GeminiResponseDto analysis) {
        List<ReportItem> items = new ArrayList<>();
        List<String> recommendations = analysis == null ? null : analysis.getFinalRecommendations();

        if (recommendations != null && !recommendations.isEmpty()) {
            int index = 1;
            for (String recommendation : recommendations) {
                items.add(new ReportItem("Recommendation " + index, recommendation));
                index++;
            }
        } else {
            items.add(new ReportItem("Recommendation", "Review missing keywords and add only the ones that honestly reflect your experience."));
        }

        return new ReportSection("9. Final Recommendations", items);
    }

    private String labeledText(Map<String, String> values, String... keys) {
        List<String> parts = new ArrayList<>();
        for (String key : keys) {
            String value = values.get(key);
            if (value != null && !value.trim().isEmpty()) {
                parts.add(labelFromKey(key) + ": " + value);
            }
        }
        return parts.isEmpty() ? "No detail provided." : String.join(" | ", parts);
    }

    private String labelFromKey(String key) {
        return switch (key) {
            case "jobRequirement" -> "Job Requirement";
            case "resumeEvidence" -> "Resume Evidence";
            case "matchLevel" -> "Match Level";
            default -> Character.toUpperCase(key.charAt(0)) + key.substring(1);
        };
    }

    private String firstValue(Map<String, String> values, String... keys) {
        for (String key : keys) {
            String value = values.get(key);
            if (value != null && !value.trim().isEmpty()) {
                return value;
            }
        }
        return "";
    }

    private String valueOrDefault(String value, String fallback) {
        return value == null || value.trim().isEmpty() ? fallback : value;
    }

    private String clean(String value) {
        return valueOrDefault(value, "").replaceAll("(?i)\\bAI\\b", "Automated");
    }

    private record ReportSection(String title, List<ReportItem> items) {}

    private record ReportItem(String label, String value) {}

    private static class PdfWriter {
        private final PDDocument document;
        private PDPage page;
        private PDPageContentStream contentStream;
        private float y;

        private PdfWriter(PDDocument document) throws IOException {
            this.document = document;
            addPage();
        }

        private void writeTitle(String text) throws IOException {
            writeText(text, PDType1Font.HELVETICA_BOLD, 22, 50, "2563EB");
            addSpace(4);
        }

        private void writeMuted(String text) throws IOException {
            writeText(text, PDType1Font.HELVETICA, 9, 50, "6B7280");
        }

        private void writeSection(ReportSection section) throws IOException {
            ensureSpace(44);
            addSpace(10);
            writeText(section.title, PDType1Font.HELVETICA_BOLD, 14, 50, "111827");
            drawRule();

            for (ReportItem item : section.items) {
                writeItem(item);
            }
        }

        private void writeItem(ReportItem item) throws IOException {
            List<String> labelLines = wrap(item.label, 24);
            List<String> valueLines = wrap(item.value, 78);
            int lineCount = Math.max(labelLines.size(), valueLines.size());
            ensureSpace(lineCount * 13 + 10);

            float rowStart = y;
            for (int i = 0; i < lineCount; i++) {
                if (i < labelLines.size()) {
                    drawLine(labelLines.get(i), PDType1Font.HELVETICA_BOLD, 9, 56, y, "111827");
                }
                if (i < valueLines.size()) {
                    drawLine(valueLines.get(i), PDType1Font.HELVETICA, 9, 210, y, "374151");
                }
                y -= 13;
            }
            y -= 5;
            drawSoftRowRule(rowStart + 5);
        }

        private void writeText(String text, PDType1Font font, int size, float x, String color) throws IOException {
            for (String line : wrap(text, 88)) {
                ensureSpace(18);
                drawLine(line, font, size, x, y, color);
                y -= size + 5;
            }
        }

        private void drawLine(String text, PDType1Font font, int size, float x, float lineY, String color) throws IOException {
            setColor(color);
            contentStream.beginText();
            contentStream.setFont(font, size);
            contentStream.newLineAtOffset(x, lineY);
            contentStream.showText(sanitizePdf(text));
            contentStream.endText();
        }

        private void drawRule() throws IOException {
            ensureSpace(12);
            contentStream.setStrokingColor(229, 231, 235);
            contentStream.moveTo(50, y);
            contentStream.lineTo(562, y);
            contentStream.stroke();
            y -= 16;
        }

        private void drawSoftRowRule(float rowY) throws IOException {
            contentStream.setStrokingColor(243, 244, 246);
            contentStream.moveTo(50, y + 2);
            contentStream.lineTo(562, y + 2);
            contentStream.stroke();
        }

        private void addSpace(float space) throws IOException {
            ensureSpace(space);
            y -= space;
        }

        private void ensureSpace(float required) throws IOException {
            if (y - required < 56) {
                addPage();
            }
        }

        private void addPage() throws IOException {
            if (contentStream != null) {
                writeFooter();
                contentStream.close();
            }

            page = new PDPage(PDRectangle.LETTER);
            document.addPage(page);
            contentStream = new PDPageContentStream(document, page);
            y = 742;
        }

        private void writeFooter() throws IOException {
            contentStream.setStrokingColor(229, 231, 235);
            contentStream.moveTo(50, 38);
            contentStream.lineTo(562, 38);
            contentStream.stroke();
            drawLine(FOOTER_TEXT, PDType1Font.HELVETICA, 8, 236, 24, "6B7280");
        }

        private void close() throws IOException {
            if (contentStream != null) {
                writeFooter();
                contentStream.close();
                contentStream = null;
            }
        }

        private void setColor(String hex) throws IOException {
            int red = Integer.parseInt(hex.substring(0, 2), 16);
            int green = Integer.parseInt(hex.substring(2, 4), 16);
            int blue = Integer.parseInt(hex.substring(4, 6), 16);
            contentStream.setNonStrokingColor(red, green, blue);
        }

        private List<String> wrap(String text, int maxChars) {
            String cleaned = sanitizePdf(text);
            if (cleaned.length() <= maxChars) {
                return List.of(cleaned);
            }

            List<String> lines = new ArrayList<>();
            StringBuilder current = new StringBuilder();
            Arrays.stream(cleaned.split("\\s+")).forEach(word -> {
                if (current.length() + word.length() + 1 > maxChars) {
                    if (current.length() > 0) {
                        lines.add(current.toString());
                        current.setLength(0);
                    }
                }
                if (current.length() > 0) {
                    current.append(' ');
                }
                current.append(word);
            });

            if (current.length() > 0) {
                lines.add(current.toString());
            }
            return lines.isEmpty() ? List.of("") : lines;
        }

        private String sanitizePdf(String text) {
            return String.valueOf(text == null ? "" : text)
                    .replaceAll("(?i)\\bAI\\b", "Automated")
                    .replaceAll("[^\\x09\\x0A\\x0D\\x20-\\x7E]", "")
                    .replace("\n", " ")
                    .trim();
        }
    }
}
